### ISSUE TITLE
FEATURE - BBSAN backup + restore

### ISSUE THREAD

**Issue by swingflip** [Classicmods/Project_Rockman#2]

**Comment by bbsan2k** [comment]
- [X] Update "psc_backup" utility to include pem key in backup archive
- [ ] Update "psc_backup" to encrypt pem with hw key in psc HW
- [ ] Update "psc_backup" to also sign LDATA backup
- [ ] Create "extract_pem" for backup restore
- [ ] Update Backup payload
- [ ] Update restore payload

**Comment by bbsan2k** [comment]
Ready for merge!
