### ISSUE TITLE
EPIC - New 32 bit kernel with OTG and network support. (combine xpad, HID and original PS1/2 controller driver if possible)

### ISSUE THREAD

**Issue by swingflip** [Classicmods/Project_Rockman#6]

**Comment by evilwraith** [comment]
These can be compiled into the kernel, no need to make them modules. 

Propose adding the following to kernel tree:

https://github.com/torvalds/linux/blob/master/drivers/input/joystick/psxpad-spi.c
https://github.com/torvalds/linux/blob/master/drivers/input/joystick/xpad.c
https://github.com/torvalds/linux/blob/master/drivers/input/joystick/Kconfig
https://github.com/torvalds/linux/blob/master/drivers/input/joystick/Makefile

**Comment by swingflip** [comment]
@GMMan can you please look at this as part of the kernel please?
